version: "3.7"

networks:
  mojaloop-net:
    name: mojaloop-net

services:
  reporting-hub-bop-experience-api-svc:
    image: mojaloop/reporting-hub-bop-experience-api-svc:local
    build:
      context: .
    ports:
      - "3001:3001"
    networks:
      - mojaloop-net
    environment:
      - BOP_EXPERIENCE_API_CENTRAL_ADMIN_URL=https://postman-echo.com