version: "3.7"

networks:
  mojaloop-net:
    name: mojaloop-net

services:
  reporting-hub-bop-experience-api-svc:
    image: mojaloop/reporting-hub-bop-experience-api-svc:local
    build:
      context: .
    ports:
      - "3001:3001"
    environment:
      - BOP_EXPERIENCE_API_CENTRAL_ADMIN_URL=http://echo-server/
      # - EVENT_SDK_SIDECAR_DISABLED=false
      # - EVENT_SDK_SERVER_HOST=sidecar
      # - EVENT_SDK_SERVER_PORT=50051

  echo-server:
    image: ealen/echo-server:latest
    environment:
      - ENABLE__ENVIRONMENT=false
    ports:
      - 3080:80

  # sidecar:
  #   image: mojaloop/event-sidecar:v11.0.1
  #   ports:
  #     - "4001:4001"
  #   environment:
  #     - LOG_LEVEL=debug
  #     - LOG_FILTER='error, warn, info'
  #     - EVENT_SDK_LOG_FILTER='audit:*, log:info, log:warn, log:error'
  #     - EVENT_SDK_LOG_METADATA_ONLY=false
  #   volumes:
  #     - ./docker/sidecar/default.json:/opt/event-sidecar/config/default.json
  #   depends_on:
  #     - kafka
  # kafka:
  #   image: johnnypark/kafka-zookeeper:2.3.0
  #   container_name: cl_kafka
  #   # Disable logging as it is far too verbose for debugging locally
  #   logging:
  #     driver: none
  #   volumes:
  #     - ./docker/kafka/:/opt/kafka_2.12-2.3.0/config/
  #   ports:
  #     - "2181:2181"
  #     - "9092:9092"
  #   environment:
  #     - ZOO_LOG4J_PROP=WARN
  #   healthcheck:
  #     test: ["CMD" ,"/opt/kafka_2.12-2.3.0/bin/kafka-broker-api-versions.sh","--bootstrap-server","localhost:9092"]
  #     timeout: 20s
  #     retries: 10
  #     start_period: 40s
  #     interval: 30s
  # kowl:
  #   image: quay.io/cloudhut/kowl:v1.4.0
  #   container_name: cl_kowl
  #   restart: on-failure
  #   hostname: kowl
  #   ports:
  #   - "8080:8080"
  #   environment:
  #     - KAFKA_BROKERS=kafka:29092
  #   depends_on:
  #     - kafka