version: "3.7"

networks:
  mojaloop-net:
    name: mojaloop-net

services:
  reporting-fin-portal-experience-svc:
    image: mojaloop/reporting-fin-portal-experience-svc:local
    build:
      context: .
    ports:
      - "3001:3001"
    networks:
      - mojaloop-net
    environment:
      - FIN_PORTAL_EXPERIENCE_SERVICE_CENTRAL_ADMIN_URL=https://postman-echo.com